### ISSUE TITLE
Creating a new Expression does not 0 out outputs from old expression

### ISSUE THREAD

**Issue by ghost** [CMU-CREATE-Lab/create-lab-visual-programmer#203]
When you make a new expression, it should turn off everything that was turned on from the last expression you were making. i.e. If I make an expression that turns on an LED, click new for a new expression, that LED from the previous expression stays on until you explicitly turn it off. It's debatable on whether this makes more sense than keeping things on.

**Comment by chrisbartley** [comment]
FWIW, I disagree with this being desirable behavior.  Is this a requested feature?

**Comment by ghost** [comment]
Someone mentioned it. In one sense it makes sense that you would want a 'clean slate' when starting a new expression but in terms of how expressions function it would also make sense to not clear them out because if you wanted that output to be off you should set it that way.

**Comment by chrisbartley** [comment]
Changing it now would break all existing sequences.  Plus it'll result in a lot of duplication of effort.  If you want an LED to remain on while executing a bunch of other commands, you'll need to keep turning the LED on in every expression.  Plus, there might be a flicker due to it getting turned off and then back on.

If people want everything off, then they could make an "All off" expression and insert it between other expressions (with an execution time of 0).

**Comment by ghost** [comment]
I think you misunderstood what I was saying. I wasn't suggesting that a non-selected box in an expression = off. I was just saying that once you create a new expression in the expression builder, that it turns off anything that got turned on from the last expression you were working with. So if you made an expression that turned on an led and then made a new expression (still in the expression editor) the led will still physically stay on on your hummingbird and it might be nice to have that turn off or have a button on the expression editor that resets all outputs to 0. This would not change how sequences or expressions are actually executed

**Comment by chrisbartley** [comment]
Ohhhh.  OK, yes, that makes more sense.  Agree a button to turn things off could be useful (I've always just created an "All Off" expression and run that when needed).  

However, I'd vote for not doing it automatically because the visual feedback of "oh, right, that LED is still on" can be useful since people typically create expressions in the order they'll be executed within a sequence.  Having things reset automatically in expression builder could be confusing once they start chaining things together in sequence builder because some users might assume the reset will happen automatically in sequence builder too.

**Comment by ghost** [comment]
Okay, so I'll close this issue and make a new one for having a reset outputs button in the expression builder

**Comment by jenncross** [comment]
Yeah I see this was closed but I'll throw my vote behind Chris, that zeroing outputs when you make an expression is not a desirable trait. Many students use this feature to make a slowly changing series of expressions where a single output is modified a little at a time. Also there is no way to know where the neutral position of a servo is ... such that setting a servo to zero could tear apart a fragile student robot.
