### ISSUE TITLE
Clear statement that unchecked output in the expression builder means that the output maintains its current value

### ISSUE THREAD

**Issue by ghost** [CMU-CREATE-Lab/create-lab-visual-programmer#206]
We've had a lot of people get confused and think that not selecting an output means it's off. It might be useful to have a label on top of non-selected outputs that says something like "maintain current value". There's plenty of space for such a label in non-selected outputs. This would make it clear to users what an unselected box means. Something like the image below (with labels being aligned)
![maintain value example](https://cloud.githubusercontent.com/assets/8027870/15834895/9bd83c4a-2bfb-11e6-90ef-79cffa839876.png)

**Comment by jenncross** [comment]
I have also seen people struggle to understand the disable/enable vs on/off
distinction. We should discuss what this should look like so that it isn't
an overload of repeated information and text.

I think shortening the text to "No Change" might help but the real issue
exists with the deeper interface metaphor and text seems like band-aid
solution.

Emily and I have a couple ideas that perhaps we can run by a few kids for
feedback....

Thanks,
Jenn

**Comment by ghost** [comment]
Issue #214 deals with this so this issue can be closed.
